name: Convert Sigma Rules to ElastAlert using sigmac

on:
  push:
    branches:
      - dev
    paths:
      - 'rules/*.yml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository của bạn chứa các rule Sigma
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Bước 2: Clone repo sigma từ SigmaHQ (với commit cụ thể)
      - name: Clone Sigma Repository
        run: |
          git clone https://github.com/SigmaHQ/legacy-sigmatools.git

      # Bước 3: Cài đặt các phụ thuộc cần thiết (nếu có)
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'



      # Bước 4: Chuyển đổi rule Sigma sang ElastAlert (sử dụng sigmac)
      - name: Convert Sigma Rules to ElastAlert format
        run: |
          mkdir -p elastalert/rules
          for file in rules/*.yml; do
            echo "Converting ${file}..."
            # Sử dụng sigmac với target elastalert và schema mapping được chỉ định trong file cấu hình,
            # ví dụ: sử dụng file sigma/tools/config/elastic_schema_config_file.yml trong repo sigma.
            sigmac -t elastalert -c ./elastic_schema_config_file.yml "$file" >> elastalert/rules/$(basename "$file")
          done

      # Bước 5: Commit và push các rule đã chuyển đổi
      - name: Commit and push converted rules
        run: |
          git config --global user.name "hanchangmeo"
          git config --global user.email "hanchiangzo@gmail.com"
          git add elastalert/rules/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-convert Sigma rules to ElastAlert format using sigmac"
            git push
          else
            echo "No changes detected."
          fi
