name: Test, Convert, and Deploy Detection Rules

on:
  push:
    branches:
      - dev  # Chạy khi có thay đổi trên nhánh dev

jobs:
  test-convert-deploy:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Bước 2: Setup Python environment
    - name: Setup Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    # Bước 3: Install Sigma dependencies
    - name: Install Sigma
      run: |
        git clone https://github.com/SigmaHQ/sigma.git
        cd sigma
        pip install sigmatools
        pip install pyyaml elasticsearch click pytest requests
        pip install sigmatools

    # Bước 4: Validate Sigma Rules
    - name: Validate Sigma Rules
      run: |
        python3 ci-scripts/validate-rule.py || exit 1

    # Bước 5: Convert Sigma Rules
    - name: Convert Sigma Rules
      run: |
        python3 ci-scripts/convert_sigma.py

    # Bước 6: Test Converted Rules
    - name: Test Converted Rules
      env:
        ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
        ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      run: |
        python3 ci-scripts/test_rules.py || exit 1

    # Bước 7: Notify Success
    - name: Notify Success
      if: success()
      run: echo "All Sigma rules passed testing. Ready for deployment."

    # Bước 8: Merge dev into main if successful
    - name: Merge dev into main
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "hanchangmeo"
        git config --global user.email "hanchiangzo@gmail.com"
        git checkout main
        git merge dev --no-edit
        git push origin main


