name: Sigma Detection Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: dev
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate Sigma Rules
        run: |
          python ci-scripts/validate_rules.py

   #   - name: Convert Sigma Rules to Elasticsearch Queries
    #    run: |
     #     python ci-scripts/convert_rules.py rules/ test/ queries/

      - name: Test Sigma Rules with Sample Logs
        run: |
          python ci-scripts/test_sigma_rules.py rules/ test/
        # Nếu không pass, pipeline dừng lại

      - name: Clone and Merge to main
        if: success()
        run: |
          git clone https://github.com/hanchangmeo/detection.git-link.github_pat_${{ secrets.PERSONAL_ACCESS_TOKEN }} temp-repo
          cd temp-repo
          git config --global user.name "hanchangmeo"
          git config --global user.email "hanchiangzo@gmail.com"
          git fetch origin
          git checkout main
          git merge origin/dev --no-ff -m "Merge validated Sigma rules from dev"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
