name: Test, Convert, and Deploy Detection Rules

on:
  push:
    branches:
      - dev  # Chạy khi có thay đổi trên nhánh dev

jobs:
  test-convert-deploy:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Bước 2: Setup Python environment
    - name: Setup Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    # Bước 3: Install Sigma
    - name: Install Sigma
      run: |
        git clone https://github.com/SigmaHQ/sigma.git
        cd sigma
        pip install -r requirements.txt

    # Bước 4: Convert Sigma Rules
    - name: Convert Sigma Rules
      run: |
        python3 ci-scripts/convert_sigma.py

    # Bước 5: Validate Converted Rules
    - name: Validate Converted Rules
      run: |
        python3 ci-scripts/validate-rules.py

    # Bước 6: Test Converted Rules on Sample Data
    - name: Test Converted Rules on Sample Data
      env:
        ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
        ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      run: |
        for file in converted-rules/*.json; do
          echo "Testing $file on sample data"
          curl -X POST "$ELASTIC_URL/_search" \
               -H "Authorization: ApiKey $ELASTIC_API_KEY" \
               -H "Content-Type: application/json" \
               -d @$file || exit 1
        done

    # Bước 7: Notify Success
    - name: Notify Success
      if: success()
      run: echo "All Sigma rules passed testing. Merging into main..."

    # Bước 8: Merge dev into main if successful
    - name: Merge dev into main
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "hanchangmeo"
        git config --global user.email "hanchiangzo@gmail.com"
        git checkout main
        git merge dev --no-edit
        git push origin main

