name: Test, Convert, and Deploy Detection Rules

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test-convert-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pySigma pysigma-backend-elasticsearch requests  # Thêm backend Elasticsearch

    - name: Verify pySigma installation
      run: |
        pip show pySigma
        pip show pysigma-backend-elasticsearch

    - name: Validate Sigma Rules
      run: python3 ci-scripts/validate-rule.py || exit 1

    - name: Convert Sigma Rules
      run: |
        python3 ci-scripts/convert_sigma.py
        ls -la converted_rules/ || echo "No files in converted_rules/"

    - name: Test Converted Rules
      env:
        ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
        ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      run: python3 ci-scripts/test_rules.py || exit 1

    - name: Deploy Rules to Elasticsearch
      if: success()
      env:
        ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
        ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      run: |
        if ls converted_rules/*.json >/dev/null 2>&1; then
          for rule_file in converted_rules/*.json; do
            echo "Deploying ${rule_file}..."
            curl -X POST "${ELASTIC_URL}/api/detection_engine/rules" \
              -H "Authorization: ApiKey ${ELASTIC_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "@${rule_file}" || exit 1
            echo "Deployed ${rule_file} successfully"
          done
        else
          echo "No JSON files found in converted_rules/. Skipping deployment."
          exit 0
        fi
