name: Sigma Detection as Code

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pysigma==0.10.0
          pip install git+https://github.com/SigmaHQ/pySigma-backend-elasticsearch.git@main
          pip install elasticsearch==8.12.1  # Compatible with Elasticsearch 8.17
          pip install PyYAML==6.0.1 requests==2.31.0 certifi urllib3

      - name: Run detection script
        env:
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
          ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: |
          python detection/ci-scripts/detect_and_alert.py
