name: Convert Sigma Rules to OpenSearch Format

on:
  push:
    branches:
      - dev
    paths:
      - rules/**    # Chỉ trigger khi có thay đổi trong thư mục rules/
  workflow_dispatch:   # Cho phép chạy thủ công

jobs:
  convert_sigma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Clone pySigma-backend-opensearch repo
        run: |
          git clone https://github.com/SigmaHQ/pySigma-backend-opensearch.git
          
      - name: Install sigma-cli and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sigma-cli
          pip install pyyaml 

      - name: Create output directory
        run: mkdir -p opensearch

      - name: Convert Sigma rules to OpenSearch format
        run: |
          python ci-scripts/sigma_to_opensearch.py

      - name: Commit and push the converted rules if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add opensearch/
          if ! git diff-index --quiet HEAD; then
              git commit -m "Auto-converted Sigma rules to OpenSearch format"
              git push
          else
              echo "No changes to commit."
          fi
